import './globals.css'
import type { Metadata } from 'next'
import Providers from './providers'
import Header from '@/components/Header'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'IMDb Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
